### ISSUE TITLE
Server Bind instruction is required when using boot2docker on a Mac

### ISSUE THREAD

**Issue by jmMeessen** [publysher/docker-hugo#2]
Hello,

Thank you for the contribution. It was an inspiration source for my own implementation.

It would be worthwhile to add a warning to the README on how to run the containerized Hugo server on some configuration,  It took me some frustrating hours to find out.

When using boot2docker (or Docker-machine with the VirtualBox provider) on a Mac OSX, the Hugo server must be started with the --bind=0.0.0.0 option as the interface bound by default (127.0.0.1) is not visible outside the virtual environement 

I suggest to update the README with that information as you already give the advise for the IP address.

**Comment by larrywright** [comment]
+1 - I ran into this issue as well (and it's the same on the newer Docker for Mac).
